name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn run build --if-present
    - run: yarn test
      env:
        CI: true

    - run: sudo apt-get install sshpass  
    - run:  /usr/bin/rsync -ratlz --rsh="/usr/bin/sshpass -p "$EGERMANO_PASS" ssh -o StrictHostKeyChecking=no -l egermano" public/  egermano@egermano:~/egermano.com/me
      if: github.ref == 'develop'
      env: 
        EGERMANO_PASS: ${{ secrets.egermano_pass }}