name: Test, Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache Yarn ./node_modules
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Yarn instal, test and build
      run: |
        yarn install
        yarn run build --if-present
        yarn test
      env:
        NODE_ENV: production
        CI: true
    - name: Deploy
      run: |
        sudo apt-get update && sudo apt-get install sshpass  -y 
        /usr/bin/rsync -vrltD --stats --human-readable --rsh="/usr/bin/sshpass -p $EGERMANO_PASS ssh -o StrictHostKeyChecking=no -l egermano" public/  egermano@ssh.egermano.com:~/egermano.com/site
      if: github.ref == 'refs/heads/master'
      env: 
        EGERMANO_PASS: ${{ secrets.egermano_pass }}